name: Python application

on:
  schedule:
    - cron: '*/5 * * * *' # 每 5 分钟运行一次
  workflow_dispatch: # 手动触发

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # 可以根据需要更改 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: pg
          path: files/PandaGroovePG
    - name: Unzip file
      run: |
        unzip -o files/PandaGroovePG/*.zip -d pg

    - name: Configure git
      run: |
        git config --global user.name "dukunjueji"
        git config --global user.email "494173758@qq.com"

    - name: Commit and push changes
      run: |
        cp -r pg/* .
        git add .
        git commit -m "Add unzipped files"
        git push origin ${{ github.ref }}
